'use client'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import ThemeRegistry from '~/app/UI/Theme'
import Navbar from '~/app/UI/Navbar'

const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const queryClient = new QueryClient()

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <link rel="icon" type="image/svg+xml" href="/snack-dash-logo.svg" />
      </head>
      <ThemeRegistry>
        <QueryClientProvider client={queryClient}>
          <body>
            <Navbar />
            {children}
          </body>
        </QueryClientProvider>
      </ThemeRegistry>
    </html>
  )
}
